// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TVManagmentSystem.DbContexti;

#nullable disable

namespace TVManagmentSystem.Migrations
{
    [DbContext(typeof(GlobalDbContext))]
    [Migration("20240128132229_mrgt")]
    partial class mrgt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TVManagmentSystem.Models.Chanell", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Chanells");
                });

            modelBuilder.Entity("TVManagmentSystem.Models.Info", b =>
                {
                    b.Property<int>("InfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoID"));

                    b.Property<int>("ChanellID")
                        .HasColumnType("int");

                    b.Property<string>("EMR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InfoID");

                    b.HasIndex("ChanellID")
                        .IsUnique();

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("TVManagmentSystem.Models.Info", b =>
                {
                    b.HasOne("TVManagmentSystem.Models.Chanell", "chan")
                        .WithOne("info")
                        .HasForeignKey("TVManagmentSystem.Models.Info", "ChanellID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chan");
                });

            modelBuilder.Entity("TVManagmentSystem.Models.Chanell", b =>
                {
                    b.Navigation("info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
